index:
  path: /dashboard/pages
  controller: Selene\Modules\PagesModule\Http\Controllers\PagesController@index
  methods:
    - GET
  permission: PagesModule

create:
  path: /dashboard/pages/create
  controller: Selene\Modules\PagesModule\Http\Controllers\PagesController@create
  methods:
    - GET
  permission: PagesModule.add

edit:
  path: /dashboard/pages/{{page}}/edit
  controller: Selene\Modules\PagesModule\Http\Controllers\PagesController@edit
  methods:
    - GET
  permission: PagesModule.edit

types:
  path: /dashboard/types
  controller: Selene\Modules\PagesModule\Http\Controllers\TypesController@index
  methods:
    - GET
  permission: PagesModule

types.create:
  path: /dashboard/types/create
  controller: Selene\Modules\PagesModule\Http\Controllers\TypesController@create
  methods:
    - GET
  permission: PagesModule.add

types.edit:
  path: /dashboard/types/{{type}}/edit
  controller: Selene\Modules\PagesModule\Http\Controllers\TypesController@edit
  methods:
    - GET
  permission: PagesModule.edit

menu:
  path: /dashboard/menu
  controller: Selene\Modules\PagesModule\Http\Controllers\MenuController@index
  methods:
    - GET
  permission: PagesModule

menu.create:
  path: /dashboard/menu/create
  controller: Selene\Modules\PagesModule\Http\Controllers\MenuController@create
  methods:
    - GET
  permission: PagesModule.add

menu.edit:
  path: /dashboard/menu/{{menu}}/edit
  controller: Selene\Modules\PagesModule\Http\Controllers\MenuController@edit
  methods:
    - GET
  permission: PagesModule.edit

page:
  path: /{{slug}}
  controller: Selene\Modules\PagesModule\Http\Controllers\PagesController@page
  methods:
    - GET
  where:
    slug: ^(?!sitemap|api).*
